defaults:
  - _self_
  - runs: proposed-iter1-Qwen3-0.6B-gsm8k

run: null

wandb:
  entity: gengaru617-personal
  project: 2025-11-13
  mode: online

mode: full  # {trial, full}
results_dir: outputs/

hydra:
  run:
    dir: ${results_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: config
  job:
    env_set:
      WANDB_CACHE_DIR: .cache/