defaults:
  - runs@run: proposed-iter1-Qwen3-0.6B-gsm8k
  - _self_

wandb:
  entity: gengaru617-personal
  project: 2025-11-13
  mode: online

mode: full  # {trial, full}
results_dir: outputs/

optuna:
  n_trials: 40
  direction: maximize
  search_space: {}

hydra:
  run:
    dir: ${results_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: config
  job:
    env_set:
      WANDB_CACHE_DIR: .cache/